### ISSUE TITLE
Add regional rollups to the analytics

### ISSUE THREAD

**Issue by timrobertson100** [gbif/analytics#16]
The current reports run global and country level.

Since GBIF run regional strategies and hold regional meetings, for which we regularly run adhoc analytics, we should aggregate the country counts to regional level based on the GBIF regions defined in the directory and available in the GBIF country enum API.

The result will be 

- [ ] regions in addition to countries on https://www.gbif.org/analytics/global
- [ ] regional breakdowns of the metrics found on https://github.com/gbif/analytics/issues/15

**Comment by MattBlissett** [comment]
Analytics project part is completed, portal work is in https://github.com/gbif/portal16/issues/1486
