### ISSUE TITLE
Adapt analytics to use the newly added multivalue fields in pipelines

### ISSUE THREAD

**Issue by marcos-lg** [gbif/analytics#21]
The issue https://github.com/gbif/pipelines/issues/665 brought some new interpreted fields and changed the typeStatus from string to array.

Some of the new fields added were used before as strings because they were being carried from the verbatim values. But now they are interpreted fields in the basic record.

You can see the changes done in the avro schemas [here](https://github.com/gbif/pipelines/commit/ddcf435a64c46d764ff22f86e7b8b178529e0461).

Analytics needs to be adapted to these changes to either use arrays or convert the arrays into strings.

**Comment by MattBlissett** [comment]
The snapshot only takes the verbatim fields: https://github.com/gbif/analytics/blob/master/hive/import/hdfs/create_hdfs_snapshot.q so I don't think there's anything to be done for analytics.
